name: xmshop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_swiper_view: ^1.1.8
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.0.17
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: xm_icon
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/images/xiaomiBanner.png
    - assets/images/xiaomiBanner2.png
    - assets/images/hot_search.png
    - assets/images/2.0x/xiaomiBanner.png
    - assets/images/3.0x/xiaomiBanner.png
    - assets/images/2.0x/hot_search.png
    - assets/images/3.0x/hot_search.png
    - assets/images/service.png
    - assets/images/2.0x/service.png
    - assets/images/3.0x/service.png